services:
  - type: web
    name: autocut
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-key-here
